### PR TITLE
Small cleanups suggested by Arthur O'Dwyer

### PR DESCRIPTION
**Pull request by thiloschulz**
There's only a few suggestions by Arthur O'Dwyer from my last pull request #71. I guess it wants to import my whole history because you last did a squash merge.

### CODE REVIEW

**Comment by tbeu** [comment]
You always should use branches for your own commits and pull requests.

**Comment by thiloschulz** [comment]
Would that have changed anything? Had I created a new branch, that branch would have still contained all of the commit history so that after Troy's squash merge the result would have been exactly the same?
I don't claim to understand git in all its complexities so feel free to correct me if I'm wrong.

**Comment by tbeu** [comment]
Certainly it would have. If you had comitted a61bdf2 to a separate branch and created the PR from this branch, this PR would not contain your previous commits to your master.

**Comment by thiloschulz** [comment]
I will close this pull request then and Troy can go with your #79. Thank you.

**Pull request closed without merging**
